Port forge 1.20.1
WildfireRomeo/WildfireFemaleGenderMod pull request #125
Opened 2023-06-14 14:36 UTC by pupnewfster

Theoretically this might support 1.20, but I didn't bother testing (nor allow it in the version bounds) as I think once two forge PRs I made are merged it would be worth using them to cleanup a couple things in the code that I had to work around. I also bounded it at forge 47.0.1 as for earlier versions forge doesn't render armor enchantment glints properly so I figured it makes sense to require that fix just so that it is less visually obtrusive to people.

Other smaller changes in this PR:
- Updated to gradle 8.1.1 and FG6 as a preventative measure against things like #41 happening again as FG6 has better reobf
- Removed WardrobeBrowserScreen#drawEntityOnScreen in favor of just calling the corresponding vanilla method
- Fixed a couple cases where translation keys weren't being used
- Made the unused toast actually get the configured keybinding instead of always claiming `G` will work
- Removed the texture cache similar to #123 as it seems to just be vanilla legacy code given the string is created every time regardless and it is just ResourceLocation creation that is cached

Opening this as a Draft for now as I am unsure if we should wait for the two forge PRs and also as there is no 1.20 branch to target yet and I am unsure of the exact naming scheme you want to use for the branch so did not create one.

2023-06-14 15:17 UTC, Kichura requested changes

2023-06-14 15:17 UTC, Kichura commented on src/main/resources/META-INF/mods.toml
>  license="GPLv3"
Please update the license to LGPLv3.

2023-06-14 15:23 UTC, pupnewfster commented on src/main/resources/META-INF/mods.toml
>  license="GPLv3"
Given the fact it literally hasn't been updated anywhere else on other branches I am going to hold off and let wildfire figure out the decision of this. Since the PR that I had seen doing it never got merged.

2023-06-15 22:39 UTC, sternschnaube commented
Could someone make please a Fabric port for 1.20.1? 😊

2023-06-15 22:47 UTC, Kichura commented
> Could someone make please a Fabric port for 1.20.1? blush

Not needed as any mod that was made for 1.20 can actually run on 1.20.1.

2023-06-22 19:08 UTC, WildfireRomeo commented
I don't know how to change this to not be a draft but I glanced over it and it looks fine to me.

2023-06-22 19:24 UTC, pupnewfster commented
Hitting the ready for review button (which I believe repo owner should be able to see). Though I will point out again that it is currently targeting the forge-1.19.3 branch so we will need to make a new branch and retarget it. Or if you want I could just push it directly, but am unsure what you would want the branch named (in terms of 1.20 or 1.20.1 given it is technically 1.20.1+ this supports)

2023-06-22 19:36 UTC, WildfireRomeo commented
Ahh gotcha, "forge-1.20.1" will work for a branch name if you wanted to push it directly.

2023-06-22 19:48 UTC, pupnewfster commented
Done, closing this as it now serves little purpose

2023-06-22 19:48 UTC, closed without merging